/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64";
import * as components from "../components";
import * as z from "zod";

export type GetBookingsBookingsLinks = {
    self?: string | undefined;
    next?: string | undefined;
    prev?: string | undefined;
};

/**
 * This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
 */
export type GetBookingsBookingsResponseBody = {
    data?: Array<components.Booking> | undefined;
    links?: GetBookingsBookingsLinks | undefined;
};

export type GetBookingsLinks = {
    self?: string | undefined;
    next?: string | undefined;
    prev?: string | undefined;
};

/**
 * This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
 */
export type GetBookingsResponseBody = {
    data?: Array<components.Booking> | undefined;
    links?: GetBookingsLinks | undefined;
};

export type GetBookingsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * A list of bookings
     */
    twoHundredApplicationJsonObject?: GetBookingsResponseBody | undefined;
    body?: Uint8Array | string | undefined;
    headers: Record<string, Array<string>>;
};

/** @internal */
export namespace GetBookingsBookingsLinks$ {
    export type Inbound = {
        self?: string | undefined;
        next?: string | undefined;
        prev?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetBookingsBookingsLinks, z.ZodTypeDef, Inbound> = z
        .object({
            self: z.string().optional(),
            next: z.string().optional(),
            prev: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.self === undefined ? null : { self: v.self }),
                ...(v.next === undefined ? null : { next: v.next }),
                ...(v.prev === undefined ? null : { prev: v.prev }),
            };
        });

    export type Outbound = {
        self?: string | undefined;
        next?: string | undefined;
        prev?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBookingsBookingsLinks> = z
        .object({
            self: z.string().optional(),
            next: z.string().optional(),
            prev: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.self === undefined ? null : { self: v.self }),
                ...(v.next === undefined ? null : { next: v.next }),
                ...(v.prev === undefined ? null : { prev: v.prev }),
            };
        });
}

/** @internal */
export namespace GetBookingsBookingsResponseBody$ {
    export type Inbound = {
        data?: Array<components.Booking$.Inbound> | undefined;
        links?: GetBookingsBookingsLinks$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetBookingsBookingsResponseBody, z.ZodTypeDef, Inbound> =
        z
            .object({
                data: z.array(components.Booking$.inboundSchema).optional(),
                links: z.lazy(() => GetBookingsBookingsLinks$.inboundSchema).optional(),
            })
            .transform((v) => {
                return {
                    ...(v.data === undefined ? null : { data: v.data }),
                    ...(v.links === undefined ? null : { links: v.links }),
                };
            });

    export type Outbound = {
        data?: Array<components.Booking$.Outbound> | undefined;
        links?: GetBookingsBookingsLinks$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetBookingsBookingsResponseBody
    > = z
        .object({
            data: z.array(components.Booking$.outboundSchema).optional(),
            links: z.lazy(() => GetBookingsBookingsLinks$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
                ...(v.links === undefined ? null : { links: v.links }),
            };
        });
}

/** @internal */
export namespace GetBookingsLinks$ {
    export type Inbound = {
        self?: string | undefined;
        next?: string | undefined;
        prev?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetBookingsLinks, z.ZodTypeDef, Inbound> = z
        .object({
            self: z.string().optional(),
            next: z.string().optional(),
            prev: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.self === undefined ? null : { self: v.self }),
                ...(v.next === undefined ? null : { next: v.next }),
                ...(v.prev === undefined ? null : { prev: v.prev }),
            };
        });

    export type Outbound = {
        self?: string | undefined;
        next?: string | undefined;
        prev?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBookingsLinks> = z
        .object({
            self: z.string().optional(),
            next: z.string().optional(),
            prev: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.self === undefined ? null : { self: v.self }),
                ...(v.next === undefined ? null : { next: v.next }),
                ...(v.prev === undefined ? null : { prev: v.prev }),
            };
        });
}

/** @internal */
export namespace GetBookingsResponseBody$ {
    export type Inbound = {
        data?: Array<components.Booking$.Inbound> | undefined;
        links?: GetBookingsLinks$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetBookingsResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: z.array(components.Booking$.inboundSchema).optional(),
            links: z.lazy(() => GetBookingsLinks$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
                ...(v.links === undefined ? null : { links: v.links }),
            };
        });

    export type Outbound = {
        data?: Array<components.Booking$.Outbound> | undefined;
        links?: GetBookingsLinks$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBookingsResponseBody> = z
        .object({
            data: z.array(components.Booking$.outboundSchema).optional(),
            links: z.lazy(() => GetBookingsLinks$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
                ...(v.links === undefined ? null : { links: v.links }),
            };
        });
}

/** @internal */
export namespace GetBookingsResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        "200_application/json_object"?: GetBookingsResponseBody$.Inbound | undefined;
        Body?: Uint8Array | string | undefined;
        Headers: Record<string, Array<string>>;
    };

    export const inboundSchema: z.ZodType<GetBookingsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            "200_application/json_object": z
                .lazy(() => GetBookingsResponseBody$.inboundSchema)
                .optional(),
            Body: b64$.zodInbound.optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v["200_application/json_object"] === undefined
                    ? null
                    : { twoHundredApplicationJsonObject: v["200_application/json_object"] }),
                ...(v.Body === undefined ? null : { body: v.Body }),
                headers: v.Headers,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        "200_application/json_object"?: GetBookingsResponseBody$.Outbound | undefined;
        Body?: Uint8Array | undefined;
        Headers: Record<string, Array<string>>;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBookingsResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            twoHundredApplicationJsonObject: z
                .lazy(() => GetBookingsResponseBody$.outboundSchema)
                .optional(),
            body: b64$.zodOutbound.optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.twoHundredApplicationJsonObject === undefined
                    ? null
                    : { "200_application/json_object": v.twoHundredApplicationJsonObject }),
                ...(v.body === undefined ? null : { Body: v.body }),
                Headers: v.headers,
            };
        });
}
