"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import links_self as components_links_self
from dataclasses_json import Undefined, dataclass_json
from traintravel import utils
from typing import Dict, List, Optional


@dataclasses.dataclass
class CreateBookingRawBookingsResponseBody:
    r"""Booking successful"""
    id: Optional[str] = dataclasses.field(default=None)
    r"""Unique identifier for the booking"""
    trip_id: Optional[str] = dataclasses.field(default=None)
    r"""Identifier of the booked trip"""
    passenger_name: Optional[str] = dataclasses.field(default=None)
    r"""Name of the passenger"""
    has_bicycle: Optional[bool] = dataclasses.field(default=None)
    r"""Indicates whether the passenger has a bicycle."""
    has_dog: Optional[bool] = dataclasses.field(default=None)
    r"""Indicates whether the passenger has a dog."""
    links: Optional[components_links_self.LinksSelf] = dataclasses.field(default=None)
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateBookingRawResponseBody:
    r"""Booking successful"""
    id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id'), 'exclude': lambda f: f is None }})
    r"""Unique identifier for the booking"""
    trip_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('trip_id'), 'exclude': lambda f: f is None }})
    r"""Identifier of the booked trip"""
    passenger_name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('passenger_name'), 'exclude': lambda f: f is None }})
    r"""Name of the passenger"""
    has_bicycle: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('has_bicycle'), 'exclude': lambda f: f is None }})
    r"""Indicates whether the passenger has a bicycle."""
    has_dog: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('has_dog'), 'exclude': lambda f: f is None }})
    r"""Indicates whether the passenger has a dog."""
    links: Optional[components_links_self.LinksSelf] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('links'), 'exclude': lambda f: f is None }})
    



@dataclasses.dataclass
class CreateBookingRawResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    headers: Dict[str, List[str]] = dataclasses.field()
    two_hundred_and_one_application_json_object: Optional[CreateBookingRawResponseBody] = dataclasses.field(default=None)
    r"""Booking successful"""
    body: Optional[bytes] = dataclasses.field(default=None)
    

