"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from typing import Dict, List


@dataclasses.dataclass
class DeleteBookingRequest:
    booking_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'bookingId', 'style': 'simple', 'explode': False }})
    r"""The ID of the booking to retrieve."""
    



@dataclasses.dataclass
class DeleteBookingResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    headers: Dict[str, List[str]] = dataclasses.field()
    

