/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type BookingInput = {
    /**
     * Identifier of the booked trip
     */
    tripId?: string | undefined;
    /**
     * Name of the passenger
     */
    passengerName?: string | undefined;
    /**
     * Indicates whether the passenger has a bicycle.
     */
    hasBicycle?: boolean | undefined;
    /**
     * Indicates whether the passenger has a dog.
     */
    hasDog?: boolean | undefined;
};

/** @internal */
export namespace BookingInput$ {
    export type Inbound = {
        trip_id?: string | undefined;
        passenger_name?: string | undefined;
        has_bicycle?: boolean | undefined;
        has_dog?: boolean | undefined;
    };

    export const inboundSchema: z.ZodType<BookingInput, z.ZodTypeDef, Inbound> = z
        .object({
            trip_id: z.string().optional(),
            passenger_name: z.string().optional(),
            has_bicycle: z.boolean().optional(),
            has_dog: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                ...(v.trip_id === undefined ? null : { tripId: v.trip_id }),
                ...(v.passenger_name === undefined ? null : { passengerName: v.passenger_name }),
                ...(v.has_bicycle === undefined ? null : { hasBicycle: v.has_bicycle }),
                ...(v.has_dog === undefined ? null : { hasDog: v.has_dog }),
            };
        });

    export type Outbound = {
        trip_id?: string | undefined;
        passenger_name?: string | undefined;
        has_bicycle?: boolean | undefined;
        has_dog?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, BookingInput> = z
        .object({
            tripId: z.string().optional(),
            passengerName: z.string().optional(),
            hasBicycle: z.boolean().optional(),
            hasDog: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                ...(v.tripId === undefined ? null : { trip_id: v.tripId }),
                ...(v.passengerName === undefined ? null : { passenger_name: v.passengerName }),
                ...(v.hasBicycle === undefined ? null : { has_bicycle: v.hasBicycle }),
                ...(v.hasDog === undefined ? null : { has_dog: v.hasDog }),
            };
        });
}
