/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type LinksBooking = {
    booking?: string | undefined;
};

/** @internal */
export namespace LinksBooking$ {
    export type Inbound = {
        booking?: string | undefined;
    };

    export const inboundSchema: z.ZodType<LinksBooking, z.ZodTypeDef, Inbound> = z
        .object({
            booking: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.booking === undefined ? null : { booking: v.booking }),
            };
        });

    export type Outbound = {
        booking?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, LinksBooking> = z
        .object({
            booking: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.booking === undefined ? null : { booking: v.booking }),
            };
        });
}
