/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = {
    oAuth2: string;
};

/** @internal */
export namespace Security$ {
    export type Inbound = {
        OAuth2: string;
    };

    export const inboundSchema: z.ZodType<Security, z.ZodTypeDef, Inbound> = z
        .object({
            OAuth2: z.string(),
        })
        .transform((v) => {
            return {
                oAuth2: v.OAuth2,
            };
        });

    export type Outbound = {
        OAuth2: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Security> = z
        .object({
            oAuth2: z.string(),
        })
        .transform((v) => {
            return {
                OAuth2: v.oAuth2,
            };
        });
}
