// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package webhooks

import (
	"traintravel/models/components"
)

type NewBookingResponse struct {
	HTTPMeta components.HTTPMetadata
	Headers  map[string][]string
}

func (o *NewBookingResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *NewBookingResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

type Links struct {
	Self *string `json:"self,omitempty"`
	Next *string `json:"next,omitempty"`
	Prev *string `json:"prev,omitempty"`
}

func (o *Links) GetSelf() *string {
	if o == nil {
		return nil
	}
	return o.Self
}

func (o *Links) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *Links) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}

type NewBookingRequestBody struct {
	// Identifier of the booked trip
	TripID *string `json:"trip_id,omitempty"`
	// Name of the passenger
	PassengerName *string `json:"passenger_name,omitempty"`
	// Indicates whether the passenger has a bicycle.
	HasBicycle *bool `json:"has_bicycle,omitempty"`
	// Indicates whether the passenger has a dog.
	HasDog *bool  `json:"has_dog,omitempty"`
	Links  *Links `json:"links,omitempty"`
}

func (o *NewBookingRequestBody) GetTripID() *string {
	if o == nil {
		return nil
	}
	return o.TripID
}

func (o *NewBookingRequestBody) GetPassengerName() *string {
	if o == nil {
		return nil
	}
	return o.PassengerName
}

func (o *NewBookingRequestBody) GetHasBicycle() *bool {
	if o == nil {
		return nil
	}
	return o.HasBicycle
}

func (o *NewBookingRequestBody) GetHasDog() *bool {
	if o == nil {
		return nil
	}
	return o.HasDog
}

func (o *NewBookingRequestBody) GetLinks() *Links {
	if o == nil {
		return nil
	}
	return o.Links
}
