// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type LinksSelf struct {
	Self *string `json:"self,omitempty"`
}

func (o *LinksSelf) GetSelf() *string {
	if o == nil {
		return nil
	}
	return o.Self
}
