// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type LinksBooking struct {
	Booking *string `json:"booking,omitempty"`
}

func (o *LinksBooking) GetBooking() *string {
	if o == nil {
		return nil
	}
	return o.Booking
}
