// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Security struct {
	OAuth2 string `security:"scheme,type=oauth2,name=Authorization"`
}

func (o *Security) GetOAuth2() string {
	if o == nil {
		return ""
	}
	return o.OAuth2
}
