// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Station struct {
	// Unique identifier for the station.
	ID string `json:"id"`
	// The name of the station
	Name string `json:"name"`
	// The address of the station.
	Address string `json:"address"`
	// The country code of the station.
	CountryCode string `json:"country_code"`
	// The timezone of the station in the [IANA Time Zone Database format](https://www.iana.org/time-zones).
	Timezone *string `json:"timezone,omitempty"`
}

func (o *Station) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Station) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Station) GetAddress() string {
	if o == nil {
		return ""
	}
	return o.Address
}

func (o *Station) GetCountryCode() string {
	if o == nil {
		return ""
	}
	return o.CountryCode
}

func (o *Station) GetTimezone() *string {
	if o == nil {
		return nil
	}
	return o.Timezone
}
