// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"time"
	"traintravel/internal/utils"
)

type Trip struct {
	// Unique identifier for the trip
	ID *string `json:"id,omitempty"`
	// The starting station of the trip
	Origin *string `json:"origin,omitempty"`
	// The destination station of the trip
	Destination *string `json:"destination,omitempty"`
	// The date and time when the trip departs
	DepartureTime *time.Time `json:"departure_time,omitempty"`
	// The date and time when the trip arrives
	ArrivalTime *time.Time `json:"arrival_time,omitempty"`
	// The name of the operator of the trip
	Operator *string `json:"operator,omitempty"`
	// The cost of the trip
	Price *float64 `json:"price,omitempty"`
	// Indicates whether bicycles are allowed on the trip
	BicyclesAllowed *bool `json:"bicycles_allowed,omitempty"`
	// Indicates whether dogs are allowed on the trip
	DogsAllowed *bool `json:"dogs_allowed,omitempty"`
}

func (t Trip) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Trip) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Trip) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Trip) GetOrigin() *string {
	if o == nil {
		return nil
	}
	return o.Origin
}

func (o *Trip) GetDestination() *string {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *Trip) GetDepartureTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.DepartureTime
}

func (o *Trip) GetArrivalTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.ArrivalTime
}

func (o *Trip) GetOperator() *string {
	if o == nil {
		return nil
	}
	return o.Operator
}

func (o *Trip) GetPrice() *float64 {
	if o == nil {
		return nil
	}
	return o.Price
}

func (o *Trip) GetBicyclesAllowed() *bool {
	if o == nil {
		return nil
	}
	return o.BicyclesAllowed
}

func (o *Trip) GetDogsAllowed() *bool {
	if o == nil {
		return nil
	}
	return o.DogsAllowed
}
