// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"traintravel/models/components"
)

// CreateBookingJSONBookingsResponseBody - Booking successful
type CreateBookingJSONBookingsResponseBody struct {
	// Unique identifier for the booking
	ID *string
	// Identifier of the booked trip
	TripID *string
	// Name of the passenger
	PassengerName *string
	// Indicates whether the passenger has a bicycle.
	HasBicycle *bool
	// Indicates whether the passenger has a dog.
	HasDog *bool
	Links  *components.LinksSelf
}

func (o *CreateBookingJSONBookingsResponseBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CreateBookingJSONBookingsResponseBody) GetTripID() *string {
	if o == nil {
		return nil
	}
	return o.TripID
}

func (o *CreateBookingJSONBookingsResponseBody) GetPassengerName() *string {
	if o == nil {
		return nil
	}
	return o.PassengerName
}

func (o *CreateBookingJSONBookingsResponseBody) GetHasBicycle() *bool {
	if o == nil {
		return nil
	}
	return o.HasBicycle
}

func (o *CreateBookingJSONBookingsResponseBody) GetHasDog() *bool {
	if o == nil {
		return nil
	}
	return o.HasDog
}

func (o *CreateBookingJSONBookingsResponseBody) GetLinks() *components.LinksSelf {
	if o == nil {
		return nil
	}
	return o.Links
}

// CreateBookingJSONResponseBody - Booking successful
type CreateBookingJSONResponseBody struct {
	// Unique identifier for the booking
	ID *string `json:"id,omitempty"`
	// Identifier of the booked trip
	TripID *string `json:"trip_id,omitempty"`
	// Name of the passenger
	PassengerName *string `json:"passenger_name,omitempty"`
	// Indicates whether the passenger has a bicycle.
	HasBicycle *bool `json:"has_bicycle,omitempty"`
	// Indicates whether the passenger has a dog.
	HasDog *bool                 `json:"has_dog,omitempty"`
	Links  *components.LinksSelf `json:"links,omitempty"`
}

func (o *CreateBookingJSONResponseBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CreateBookingJSONResponseBody) GetTripID() *string {
	if o == nil {
		return nil
	}
	return o.TripID
}

func (o *CreateBookingJSONResponseBody) GetPassengerName() *string {
	if o == nil {
		return nil
	}
	return o.PassengerName
}

func (o *CreateBookingJSONResponseBody) GetHasBicycle() *bool {
	if o == nil {
		return nil
	}
	return o.HasBicycle
}

func (o *CreateBookingJSONResponseBody) GetHasDog() *bool {
	if o == nil {
		return nil
	}
	return o.HasDog
}

func (o *CreateBookingJSONResponseBody) GetLinks() *components.LinksSelf {
	if o == nil {
		return nil
	}
	return o.Links
}

type CreateBookingJSONResponse struct {
	HTTPMeta components.HTTPMetadata
	// Booking successful
	TwoHundredAndOneApplicationJSONObject *CreateBookingJSONResponseBody
	Body                                  []byte
	Headers                               map[string][]string
}

func (o *CreateBookingJSONResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateBookingJSONResponse) GetTwoHundredAndOneApplicationJSONObject() *CreateBookingJSONResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredAndOneApplicationJSONObject
}

func (o *CreateBookingJSONResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *CreateBookingJSONResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
