// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"traintravel/models/components"
)

type DeleteBookingRequest struct {
	// The ID of the booking to retrieve.
	BookingID string `pathParam:"style=simple,explode=false,name=bookingId"`
}

func (o *DeleteBookingRequest) GetBookingID() string {
	if o == nil {
		return ""
	}
	return o.BookingID
}

type DeleteBookingResponse struct {
	HTTPMeta components.HTTPMetadata
	Headers  map[string][]string
}

func (o *DeleteBookingResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteBookingResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
