// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"traintravel/models/components"
)

type GetBookingsBookingsLinks struct {
	Self *string
	Next *string
	Prev *string
}

func (o *GetBookingsBookingsLinks) GetSelf() *string {
	if o == nil {
		return nil
	}
	return o.Self
}

func (o *GetBookingsBookingsLinks) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *GetBookingsBookingsLinks) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}

// GetBookingsBookingsResponseBody - This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
type GetBookingsBookingsResponseBody struct {
	Data  []components.Booking
	Links *GetBookingsBookingsLinks
}

func (o *GetBookingsBookingsResponseBody) GetData() []components.Booking {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetBookingsBookingsResponseBody) GetLinks() *GetBookingsBookingsLinks {
	if o == nil {
		return nil
	}
	return o.Links
}

type GetBookingsLinks struct {
	Self *string `json:"self,omitempty"`
	Next *string `json:"next,omitempty"`
	Prev *string `json:"prev,omitempty"`
}

func (o *GetBookingsLinks) GetSelf() *string {
	if o == nil {
		return nil
	}
	return o.Self
}

func (o *GetBookingsLinks) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *GetBookingsLinks) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}

// GetBookingsResponseBody - This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
type GetBookingsResponseBody struct {
	Data  []components.Booking `json:"data,omitempty"`
	Links *GetBookingsLinks    `json:"links,omitempty"`
}

func (o *GetBookingsResponseBody) GetData() []components.Booking {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetBookingsResponseBody) GetLinks() *GetBookingsLinks {
	if o == nil {
		return nil
	}
	return o.Links
}

type GetBookingsResponse struct {
	HTTPMeta components.HTTPMetadata
	// A list of bookings
	TwoHundredApplicationJSONObject *GetBookingsResponseBody
	Body                            []byte
	Headers                         map[string][]string
}

func (o *GetBookingsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetBookingsResponse) GetTwoHundredApplicationJSONObject() *GetBookingsResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *GetBookingsResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *GetBookingsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
