// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"traintravel/models/components"
)

type GetStationsLinks struct {
	Self *string
	Next *string
	Prev *string
}

func (o *GetStationsLinks) GetSelf() *string {
	if o == nil {
		return nil
	}
	return o.Self
}

func (o *GetStationsLinks) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *GetStationsLinks) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}

// GetStationsStationsResponseBody - This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
type GetStationsStationsResponseBody struct {
	Data  []components.Station
	Links *GetStationsLinks
}

func (o *GetStationsStationsResponseBody) GetData() []components.Station {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetStationsStationsResponseBody) GetLinks() *GetStationsLinks {
	if o == nil {
		return nil
	}
	return o.Links
}

type Links struct {
	Self *string `json:"self,omitempty"`
	Next *string `json:"next,omitempty"`
	Prev *string `json:"prev,omitempty"`
}

func (o *Links) GetSelf() *string {
	if o == nil {
		return nil
	}
	return o.Self
}

func (o *Links) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *Links) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}

// GetStationsResponseBody - This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
type GetStationsResponseBody struct {
	Data  []components.Station `json:"data,omitempty"`
	Links *Links               `json:"links,omitempty"`
}

func (o *GetStationsResponseBody) GetData() []components.Station {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetStationsResponseBody) GetLinks() *Links {
	if o == nil {
		return nil
	}
	return o.Links
}

type GetStationsResponse struct {
	HTTPMeta components.HTTPMetadata
	// A list of train stations
	TwoHundredApplicationJSONObject *GetStationsResponseBody
	Body                            []byte
	Headers                         map[string][]string
}

func (o *GetStationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetStationsResponse) GetTwoHundredApplicationJSONObject() *GetStationsResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *GetStationsResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *GetStationsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
