/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks";
import * as b64$ from "../lib/base64";
import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import * as enc$ from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import * as schemas$ from "../lib/schemas";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import * as components from "../models/components";
import * as errors from "../models/errors";
import * as operations from "../models/operations";

export enum GetBookingsAcceptEnum {
    applicationJson = "application/json",
    applicationXml = "application/xml",
}

export enum CreateBookingJsonAcceptEnum {
    applicationJson = "application/json",
    applicationXml = "application/xml",
}

export enum CreateBookingRawAcceptEnum {
    applicationJson = "application/json",
    applicationXml = "application/xml",
}

export enum GetBookingAcceptEnum {
    applicationJson = "application/json",
    applicationXml = "application/xml",
}

export class Bookings extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * List existing bookings
     *
     * @remarks
     * Returns a list of all trips booking by the authenticated user.
     */
    async getBookings(
        options?: RequestOptions & { acceptHeaderOverride?: GetBookingsAcceptEnum }
    ): Promise<operations.GetBookingsResponse> {
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);

        const accept = options?.acceptHeaderOverride || "application/json;q=1, application/xml;q=0";
        headers$.set("Accept", accept);

        const path$ = this.templateURLComponent("/bookings")();

        const query$ = "";

        let security$;
        if (typeof this.options$.oAuth2 === "function") {
            security$ = { oAuth2: await this.options$.oAuth2() };
        } else if (this.options$.oAuth2) {
            security$ = { oAuth2: this.options$.oAuth2 };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "get-bookings",
            oAuth2Scopes: [],
            securitySource: this.options$.oAuth2,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = {
            context,
            errorCodes: ["400", "401", "403", "429", "4XX", "500", "5XX"],
        };
        const request = this.createRequest$(
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
            },
            options
        );

        const response = await this.do$(request, doOptions);

        const responseFields$ = {
            HttpMeta: {
                Response: response,
                Request: request,
            },
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = schemas$.parse(
                responseBody,
                (val$) => {
                    return operations.GetBookingsResponse$.inboundSchema.parse({
                        ...responseFields$,
                        Headers: this.unpackHeaders(response.headers),
                        "200_application/json_object": val$,
                    });
                },
                "Response validation failed"
            );
            return result;
        } else if (this.matchResponse(response, 200, "application/xml")) {
            const responseBody = await response.arrayBuffer();
            const result = schemas$.parse(
                new Uint8Array(responseBody),
                (val$) => {
                    return operations.GetBookingsResponse$.inboundSchema.parse({
                        ...responseFields$,
                        Headers: this.unpackHeaders(response.headers),
                        Body: val$,
                    });
                },
                "Response validation failed"
            );
            return result;
        } else if (this.matchStatusCode(response, [400, 401, 403, 429, 500])) {
            return schemas$.parse(
                this.unpackHeaders(response.headers),
                (val$) =>
                    operations.GetBookingsResponse$.inboundSchema.parse({
                        ...responseFields$,
                        Headers: val$,
                    }),
                "Response validation failed"
            );
        } else {
            throw new errors.SDKError("Unexpected API response", { response, request });
        }
    }

    /**
     * Create a booking
     *
     * @remarks
     * A booking is a temporary hold on a trip. It is not confirmed until the payment is processed.
     */
    async createBookingJson(
        input: components.BookingInput,
        options?: RequestOptions & { acceptHeaderOverride?: CreateBookingJsonAcceptEnum }
    ): Promise<operations.CreateBookingJsonResponse> {
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");

        const accept = options?.acceptHeaderOverride || "application/json;q=1, application/xml;q=0";
        headers$.set("Accept", accept);

        const payload$ = schemas$.parse(
            input,
            (value$) => components.BookingInput$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = enc$.encodeJSON("body", payload$, { explode: true });

        const path$ = this.templateURLComponent("/bookings")();

        const query$ = "";

        let security$;
        if (typeof this.options$.oAuth2 === "function") {
            security$ = { oAuth2: await this.options$.oAuth2() };
        } else if (this.options$.oAuth2) {
            security$ = { oAuth2: this.options$.oAuth2 };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "create-booking_json",
            oAuth2Scopes: [],
            securitySource: this.options$.oAuth2,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = {
            context,
            errorCodes: ["400", "401", "404", "409", "429", "4XX", "500", "5XX"],
        };
        const request = this.createRequest$(
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request, doOptions);

        const responseFields$ = {
            HttpMeta: {
                Response: response,
                Request: request,
            },
        };

        if (this.matchResponse(response, 201, "application/json")) {
            const responseBody = await response.json();
            const result = schemas$.parse(
                responseBody,
                (val$) => {
                    return operations.CreateBookingJsonResponse$.inboundSchema.parse({
                        ...responseFields$,
                        "201_application/json_object": val$,
                    });
                },
                "Response validation failed"
            );
            return result;
        } else if (this.matchResponse(response, 201, "application/xml")) {
            const responseBody = await response.arrayBuffer();
            const result = schemas$.parse(
                new Uint8Array(responseBody),
                (val$) => {
                    return operations.CreateBookingJsonResponse$.inboundSchema.parse({
                        ...responseFields$,
                        Body: val$,
                    });
                },
                "Response validation failed"
            );
            return result;
        } else if (this.matchStatusCode(response, [400, 401, 404, 409, 429, 500])) {
            return schemas$.parse(
                this.unpackHeaders(response.headers),
                (val$) =>
                    operations.CreateBookingJsonResponse$.inboundSchema.parse({
                        ...responseFields$,
                        Headers: val$,
                    }),
                "Response validation failed"
            );
        } else {
            throw new errors.SDKError("Unexpected API response", { response, request });
        }
    }

    /**
     * Create a booking
     *
     * @remarks
     * A booking is a temporary hold on a trip. It is not confirmed until the payment is processed.
     */
    async createBookingRaw(
        input: Uint8Array | string,
        options?: RequestOptions & { acceptHeaderOverride?: CreateBookingRawAcceptEnum }
    ): Promise<operations.CreateBookingRawResponse> {
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/xml");

        const accept = options?.acceptHeaderOverride || "application/json;q=1, application/xml;q=0";
        headers$.set("Accept", accept);

        const payload$ = schemas$.parse(
            input,
            (value$) => b64$.zodOutbound.parse(value$),
            "Input validation failed"
        );
        const body$ = payload$;

        const path$ = this.templateURLComponent("/bookings")();

        const query$ = "";

        let security$;
        if (typeof this.options$.oAuth2 === "function") {
            security$ = { oAuth2: await this.options$.oAuth2() };
        } else if (this.options$.oAuth2) {
            security$ = { oAuth2: this.options$.oAuth2 };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "create-booking_raw",
            oAuth2Scopes: [],
            securitySource: this.options$.oAuth2,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = {
            context,
            errorCodes: ["400", "401", "404", "409", "429", "4XX", "500", "5XX"],
        };
        const request = this.createRequest$(
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request, doOptions);

        const responseFields$ = {
            HttpMeta: {
                Response: response,
                Request: request,
            },
        };

        if (this.matchResponse(response, 201, "application/json")) {
            const responseBody = await response.json();
            const result = schemas$.parse(
                responseBody,
                (val$) => {
                    return operations.CreateBookingRawResponse$.inboundSchema.parse({
                        ...responseFields$,
                        "201_application/json_object": val$,
                    });
                },
                "Response validation failed"
            );
            return result;
        } else if (this.matchResponse(response, 201, "application/xml")) {
            const responseBody = await response.arrayBuffer();
            const result = schemas$.parse(
                new Uint8Array(responseBody),
                (val$) => {
                    return operations.CreateBookingRawResponse$.inboundSchema.parse({
                        ...responseFields$,
                        Body: val$,
                    });
                },
                "Response validation failed"
            );
            return result;
        } else if (this.matchStatusCode(response, [400, 401, 404, 409, 429, 500])) {
            return schemas$.parse(
                this.unpackHeaders(response.headers),
                (val$) =>
                    operations.CreateBookingRawResponse$.inboundSchema.parse({
                        ...responseFields$,
                        Headers: val$,
                    }),
                "Response validation failed"
            );
        } else {
            throw new errors.SDKError("Unexpected API response", { response, request });
        }
    }

    /**
     * Get a booking
     *
     * @remarks
     * Returns the details of a specific booking.
     */
    async getBooking(
        bookingId: string,
        options?: RequestOptions & { acceptHeaderOverride?: GetBookingAcceptEnum }
    ): Promise<operations.GetBookingResponse> {
        const input$: operations.GetBookingRequest = {
            bookingId: bookingId,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);

        const accept = options?.acceptHeaderOverride || "application/json;q=1, application/xml;q=0";
        headers$.set("Accept", accept);

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetBookingRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            bookingId: enc$.encodeSimple("bookingId", payload$.bookingId, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/bookings/{bookingId}")(pathParams$);

        const query$ = "";

        let security$;
        if (typeof this.options$.oAuth2 === "function") {
            security$ = { oAuth2: await this.options$.oAuth2() };
        } else if (this.options$.oAuth2) {
            security$ = { oAuth2: this.options$.oAuth2 };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "get-booking",
            oAuth2Scopes: [],
            securitySource: this.options$.oAuth2,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = {
            context,
            errorCodes: ["400", "401", "403", "404", "429", "4XX", "500", "5XX"],
        };
        const request = this.createRequest$(
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request, doOptions);

        const responseFields$ = {
            HttpMeta: {
                Response: response,
                Request: request,
            },
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = schemas$.parse(
                responseBody,
                (val$) => {
                    return operations.GetBookingResponse$.inboundSchema.parse({
                        ...responseFields$,
                        Headers: this.unpackHeaders(response.headers),
                        "200_application/json_object": val$,
                    });
                },
                "Response validation failed"
            );
            return result;
        } else if (this.matchResponse(response, 200, "application/xml")) {
            const responseBody = await response.arrayBuffer();
            const result = schemas$.parse(
                new Uint8Array(responseBody),
                (val$) => {
                    return operations.GetBookingResponse$.inboundSchema.parse({
                        ...responseFields$,
                        Headers: this.unpackHeaders(response.headers),
                        Body: val$,
                    });
                },
                "Response validation failed"
            );
            return result;
        } else if (this.matchStatusCode(response, [400, 401, 403, 404, 429, 500])) {
            return schemas$.parse(
                this.unpackHeaders(response.headers),
                (val$) =>
                    operations.GetBookingResponse$.inboundSchema.parse({
                        ...responseFields$,
                        Headers: val$,
                    }),
                "Response validation failed"
            );
        } else {
            throw new errors.SDKError("Unexpected API response", { response, request });
        }
    }

    /**
     * Delete a booking
     *
     * @remarks
     * Deletes a booking, cancelling the hold on the trip.
     */
    async deleteBooking(
        bookingId: string,
        options?: RequestOptions
    ): Promise<operations.DeleteBookingResponse> {
        const input$: operations.DeleteBookingRequest = {
            bookingId: bookingId,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "*/*");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.DeleteBookingRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            bookingId: enc$.encodeSimple("bookingId", payload$.bookingId, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/bookings/{bookingId}")(pathParams$);

        const query$ = "";

        let security$;
        if (typeof this.options$.oAuth2 === "function") {
            security$ = { oAuth2: await this.options$.oAuth2() };
        } else if (this.options$.oAuth2) {
            security$ = { oAuth2: this.options$.oAuth2 };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "delete-booking",
            oAuth2Scopes: [],
            securitySource: this.options$.oAuth2,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = {
            context,
            errorCodes: ["400", "401", "403", "404", "429", "4XX", "500", "5XX"],
        };
        const request = this.createRequest$(
            {
                security: securitySettings$,
                method: "DELETE",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request, doOptions);

        const responseFields$ = {
            HttpMeta: {
                Response: response,
                Request: request,
            },
        };

        if (this.matchStatusCode(response, 204)) {
            // fallthrough
        } else if (this.matchStatusCode(response, [400, 401, 403, 404, 429, 500])) {
            return schemas$.parse(
                this.unpackHeaders(response.headers),
                (val$) =>
                    operations.DeleteBookingResponse$.inboundSchema.parse({
                        ...responseFields$,
                        Headers: val$,
                    }),
                "Response validation failed"
            );
        } else {
            throw new errors.SDKError("Unexpected API response", { response, request });
        }

        return schemas$.parse(
            undefined,
            () => operations.DeleteBookingResponse$.inboundSchema.parse(responseFields$),
            "Response validation failed"
        );
    }
}
