/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks";
import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import * as enc$ from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import * as schemas$ from "../lib/schemas";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import * as components from "../models/components";
import * as errors from "../models/errors";
import * as operations from "../models/operations";

export class Payments extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Pay for a Booking
     *
     * @remarks
     * A payment is an attempt to pay for the booking, which will confirm the booking for the user and enable them to get their tickets.
     */
    async createBookingPayment(
        bookingId: string,
        bookingPayment?: components.BookingPayment | undefined,
        options?: RequestOptions
    ): Promise<operations.CreateBookingPaymentResponse> {
        const input$: operations.CreateBookingPaymentRequest = {
            bookingId: bookingId,
            bookingPayment: bookingPayment,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.CreateBookingPaymentRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = enc$.encodeJSON("body", payload$.BookingPayment, { explode: true });

        const pathParams$ = {
            bookingId: enc$.encodeSimple("bookingId", payload$.bookingId, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/bookings/{bookingId}/payment")(pathParams$);

        const query$ = "";

        let security$;
        if (typeof this.options$.oAuth2 === "function") {
            security$ = { oAuth2: await this.options$.oAuth2() };
        } else if (this.options$.oAuth2) {
            security$ = { oAuth2: this.options$.oAuth2 };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "create-booking-payment",
            oAuth2Scopes: [],
            securitySource: this.options$.oAuth2,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = {
            context,
            errorCodes: ["400", "401", "403", "429", "4XX", "500", "5XX"],
        };
        const request = this.createRequest$(
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request, doOptions);

        const responseFields$ = {
            HttpMeta: {
                Response: response,
                Request: request,
            },
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = schemas$.parse(
                responseBody,
                (val$) => {
                    return operations.CreateBookingPaymentResponse$.inboundSchema.parse({
                        ...responseFields$,
                        Headers: this.unpackHeaders(response.headers),
                        object: val$,
                    });
                },
                "Response validation failed"
            );
            return result;
        } else if (this.matchStatusCode(response, [400, 401, 403, 429, 500])) {
            return schemas$.parse(
                this.unpackHeaders(response.headers),
                (val$) =>
                    operations.CreateBookingPaymentResponse$.inboundSchema.parse({
                        ...responseFields$,
                        Headers: val$,
                    }),
                "Response validation failed"
            );
        } else {
            throw new errors.SDKError("Unexpected API response", { response, request });
        }
    }
}
